const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, 'assets');
const OUTPUT_FILE = path.join(__dirname, 'assets.js');

function buildAssets() {
  try {
    const files = fs.readdirSync(ASSETS_DIR)
      .filter(name => name.endsWith('.svg'))
      .sort();

    if (files.length === 0) {
      console.warn('No .svg files found in assets/');
      return;
    }

    const assetsMap = {};
    for (const file of files) {
      const key = file.replace(/\.svg$/, '');
      const data = fs.readFileSync(path.join(ASSETS_DIR, file), 'utf-8');
      const base64 = Buffer.from(data, 'utf-8').toString('base64');
      assetsMap[key] = `data:image/svg+xml;base64,${base64}`;
      console.log(`  → ${file} (${key})`);
    }

    const lines = [
      '// Auto-generated by build-assets.js — do not edit manually',
      '// Run: node build-assets.js',
      `// Generated: ${new Date().toISOString()}`,
      '',
      'const ASSETS = {',
    ];
    for (const [key, uri] of Object.entries(assetsMap)) {
      lines.push(`  '${key}': '${uri}',`);
    }
    lines.push('  _count: ' + files.length);
    lines.push('};');
    lines.push('');
    lines.push('window.ASSETS_ASSETS = ASSETS;');
    lines.push('');

    fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8');
    console.log(`\n✓ Wrote ${files.length} assets to ${OUTPUT_FILE}`);
  } catch (err) {
    console.error('Build failed:', err.message);
    process.exit(1);
  }
}

buildAssets();
